name: Test

env:
  GO_VERSION: '1.25'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: â¬‡ï¸ Download dependencies
        run: go mod download

      - name: â¬‡ï¸ Verify dependencies
        run: go mod verify

      - name: ğŸ› ï¸ Build lib
        run: go build -v ./...

      - name: ğŸƒ Run tests
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...

      - name: ğŸ“Š Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

      - name: ğŸ“Š Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: qeeqez/work-email-validator

  gostatic:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ğŸƒ Run staticcheck
        uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "latest"
          install-go: false

  govet:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ğŸƒ Run go vet
        run: go vet ./...

  security:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ğŸƒ Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v6

      - name: â¬‡ï¸ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ğŸƒ Run linter
        uses: golangci/golangci-lint-action@v9